// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEvb3bpdD5Pn-yyNdmi1ytdGoVa1n-ddQ',
    appId: '1:1047700084869:web:147b2910c082fc6fcc31ec',
    messagingSenderId: '1047700084869',
    projectId: 'prototypetest-aed9e',
    authDomain: 'prototypetest-aed9e.firebaseapp.com',
    storageBucket: 'prototypetest-aed9e.firebasestorage.app',
    measurementId: 'G-HW5NQW69HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArADB_4TCeO0YlKvMGA6JO67L4AONM52E',
    appId: '1:1047700084869:android:8849705ca7cf77adcc31ec',
    messagingSenderId: '1047700084869',
    projectId: 'prototypetest-aed9e',
    storageBucket: 'prototypetest-aed9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjHaOWj7ACxIVt3-WuaDyKBIQuC6B3g_o',
    appId: '1:1047700084869:ios:4659e1aca25f8475cc31ec',
    messagingSenderId: '1047700084869',
    projectId: 'prototypetest-aed9e',
    storageBucket: 'prototypetest-aed9e.firebasestorage.app',
    iosBundleId: 'com.example.appScreenTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjHaOWj7ACxIVt3-WuaDyKBIQuC6B3g_o',
    appId: '1:1047700084869:ios:4659e1aca25f8475cc31ec',
    messagingSenderId: '1047700084869',
    projectId: 'prototypetest-aed9e',
    storageBucket: 'prototypetest-aed9e.firebasestorage.app',
    iosBundleId: 'com.example.appScreenTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEvb3bpdD5Pn-yyNdmi1ytdGoVa1n-ddQ',
    appId: '1:1047700084869:web:205e4f02c01bdf2ecc31ec',
    messagingSenderId: '1047700084869',
    projectId: 'prototypetest-aed9e',
    authDomain: 'prototypetest-aed9e.firebaseapp.com',
    storageBucket: 'prototypetest-aed9e.firebasestorage.app',
    measurementId: 'G-NEEBBDYZ7L',
  );

}